In [ ]:
#  Traigo las clases que armamos en los otros archivos sueltos
from traer_datos import CargadorHF
from hacer_resumen import ResumidorDataset

c:\Users\juand\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
# Cargo el dataset Iris de Hugging Face usando nuestra clase
conector = CargadorHF(dataset_id='scikit-learn/iris', split_name='train')

# Guardamos los datos originales aca
df_original = conector.obtener_dataframe()

# Mostramos las primeras filas para verificar que todo cargo bien
df_original.head()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
c:\Users\juand\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\juand\.cache\huggingface\hub\datasets--scikit-learn--iris. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Generating train split: 100%|██████████| 150/150 [00:00<00:00, 9485.80 examples/s]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
# Cambio los nombres de las columnas a español para que se entienda mejor
diccionario_nombres = {
    'Id': 'id',
    'SepalLengthCm': 'largo_sepalo',
    'SepalWidthCm': 'ancho_sepalo',
    'PetalLengthCm': 'largo_petalo',
    'PetalWidthCm': 'ancho_petalo',
    'Species': 'especie'
}

# Aplico el renombrado en un dataframe nuevo
df_transformado = df_original.rename(columns=diccionario_nombres)

# Muestro los primeros datos modificados
df_transformado.head()

   id  largo_sepalo  ancho_sepalo  largo_petalo  ancho_petalo      especie
0   1           5.1           3.5           1.4           0.2  Iris-setosa
1   2           4.9           3.0           1.4           0.2  Iris-setosa
2   3           4.7           3.2           1.3           0.2  Iris-setosa
3   4           4.6           3.1           1.5           0.2  Iris-setosa
4   5           5.0           3.6           1.4           0.2  Iris-setosa

In [6]:
# Llamo al resumidor y le paso la tabla con los nombres nuevos
analizador = ResumidorDataset(df_transformado)

# Le digo que cree el archivo de texto final con el resumen
analizador.guardar_resumen_txt("resumen_dataset.txt")